description: >
  This is a sample executor using an Ubuntu base image

docker:
  - image: 'cimg/base:<<parameters.tag>>'
  
parameters:
  tag:
    default: stable
    description: >
      Pick a specific image version tag. See here for more details: https://circleci.com/developer/images/image/cimg/base
    type: string
